[build]
  functions = "functions"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/src/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"